const $TeacherTrainingBlogsData =[

    {
        id:1,
        post_title:'Movement Principle', 
        post_img_link:'#',
        post_imgsrc:'assets/img/movement.png',
        post_title_link:'#',
        post_description:'Learn how to recognize, improve and teach fundamental movement patterns with the Movement',
        post_btn_link:'#',
    },
    {
        id:2,
        post_title:'Mat 1 (Basic)',
        post_img_link:'#',
        post_imgsrc:'assets/img/mat-1.png',
        post_title_link:'#',
        post_description:'Foundation of the Pilates method; it includes an introduction to the principles of the Pilates method.',
        post_btn_link:'#',
    },
    {
        id:3,
        post_title:'Mat 2 (Intermediate)',
        post_img_link:'#',
        post_imgsrc:'assets/img/matt-2.png',
        post_title_link:'#',
        post_description:'Intermediate and advanced level Mat exercises for a complete understanding of the Mat program.',
        post_btn_link:'#',
    },
    {
        id:4,
        post_title:'Mat 3',
        post_img_link:'#',
        post_imgsrc:'assets/img/matt-3.png',
        post_title_link:'#',
        post_description:'Enhanced Pilates Mat completes the mat training by adding rings, rollers, bands and balls to the traditional Mat exercises.',
        post_btn_link:'#',
    },
    {
        id:5,
        post_title:'Reformer 1 (Basic)',
        post_img_link:'#',
        post_imgsrc:'assets/img/reformer-1.png',
        post_title_link:'#',
        post_description:'This course introduces the Universal Reformer, the center piece of the Pilates equipment studio and an invaluable training tool.',
        post_btn_link:'#',
    },
    {
        id:6,
        post_title:'Reformer 2 (Intermediate)',
        post_img_link:'#',
        post_imgsrc:'assets/img/reformer-2.png',
        post_title_link:'#',
        post_description:'Reformer 2 expands the potential of the Reformer with intermediate and advanced exercises and modifications, along with programme designs.',
        post_btn_link:'#',
    },
    {
        id:7,
        post_title:'Reformer 3',
        post_img_link:'#',
        post_imgsrc:'assets/img/reformer-3.png',
        post_title_link:'#',
        post_description:'Reformer 3 is the pinnacle of the Reformer work and includes advanced and super advanced exercises for best results.',
        post_btn_link:'#',
    },
    {
        id:8,
        post_title:'Trapeze Table',
        post_img_link:'#',
        post_imgsrc:'assets/img/trapezetable.png',
        post_title_link:'#',
        post_description:'Introduction to Trapeze Table and Tower exercises as well as applications for beginning, post–rehabilitation and advanced clients.',
        post_btn_link:'#',
    },
    {
        id:9,
        post_title:'Chair',
        post_img_link:'#',
        post_imgsrc:'assets/img/chair.png',
        post_title_link:'#',
        post_description:'Chair Pilates includes exercises and variations for the original Wunda chair, the EXO chair and the split pedal Combo Chair.',
        post_btn_link:'#',
    },
    
    
];

export default $TeacherTrainingBlogsData
